#!/usr/bin/env bash
#
# Deploy snapshot to github

set -e

pushd $(dirname $0)

pushd ../../github/snapshots
git clean -f
popd

mvn deploy

pushd ../../github/snapshots
git add .
git commit -am "Update Snapshot Builds"
git push
popd

popd

echo "Done."